config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  # sign_up 
  post    'sign_up' => "registrations#create" 
  # sign_in
  get 		'login' => 'sessions#new'
  post 		'login' => 'sessions#create'
  delete 	'logout' => 'sessions#destroy'

  namespace :api do
    namespace :wechat do
      post :auth
    end
    post "upload" => "base#upload"
    resources :valid_codes, only: [:create] do
      collection do
        post :valid
      end
    end
  	resources :registrations, only: [:create]
  	resources :sessions, only: [:create]

    namespace :auth do
      get :cgj
    end
    
    namespace :sync do
      resources :orders, only: [] do
        collection do
          post :update_cgj
        end
      end
      resources :customers, only: [:create]
      resources :accounts, only: [] do
        collection do
          post :gen_account_user
          post :update_cgj
        end
      end
    end

	  resources :users do # 用户管理
      collection do
        post :update_me
        post :update_password
        post :reset_password
        get  :bank_cards
        post :add_bank_card
        post :update_bank_card
        get  :statistics
        post :update_me_wx # 小程序
      end
    end
	  resources :clues do # 线索管理
      collection do
        post :update_me
        post :assign
        post :add_remark
      end
    end

    resources :regions, only: [:index, :create, :show] do
      resources :stores, only: [:index, :create, :update]
      resources :region_strategies, only: [:index, :create, :update, :destroy]
    end
    post "stores/:id" => "stores#update"
  	
    post "orders/:id/upload_file" => "orders#upload_file"
    post "orders/:id/check_order" => "orders#check_order"
    post "orders/:id/delete_pictures" => "orders#delete_pictures"
  	resources :orders do # 订单管理
      collection do
        get :get_cgjs
        post :update_estimated_total
        post :update_rebate
        get :fetch_users
      end
    end
  	resources :customers do # 客户管理 
      member do
        post :update
      end
    end
    resources :strategies do # 策略管理
      member do
        post :update
      end
    end
    resources :accounts do
      collection do
        get :get_directors
        get :companies
        post :add_company
        post :apply_co_companies
        post :update_apply
        post :update_me
      end
    end
    resources :pres, only: [:index]

    resources :wallets, only: [] do
      collection do
        get :me
        get  :config
        post :recharge
        post :withdraw
      end
    end

    resources :strategy_results, only: [:index, :show] do
      member do
        post :update
        post :pay
      end
    end

    resources :suggestions
	end

  resources :payments, only: [] do
    collection do
      post :callback
    end
  end

  namespace :admin do
    resources :users
    resources :orders
    resources :clues
    resources :wallet_logs, only: [:index] do
      member do
        put :confirm_pay
      end
    end
    resources :suggestions
  end

end

app/models/wallet_log.rb
# == Schema Information
#
# Table name: wallet_logs
#
#  id                 :integer          not null, primary key
#  transfer           :integer          not null
#  state              :integer          not null
#  trade_type         :string
#  charge_id          :string
#  amount             :float
#  total              :float
#  strategy_result_id :integer
#  user_id            :integer          not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  account_number     :string
#  account_bank       :string
#  account_branch     :string
#  account_name       :string
#  paid               :boolean          default(FALSE)
#

class WalletLog < ActiveRecord::Base

  include Pingppable

	belongs_to :user
  belongs_to :strategy_result

	STATE = {
    -1 => 'invalid',
    0  => 'prehead',
    1  => 'completed'
  }
  TRANSFER = {
    0  => '存进',       # 存进
    1  => '支出',       # 支出
    2  => '收入',       # 收入
    3  => '提现',       # 提现
  }

  validates :trade_type, inclusion: {in: [nil, 'alipay', 'alipay_pc_direct', 'local', 'wx_pub'], message: '不在所选范围之内'} 

  validates_numericality_of :amount, greater_than_or_equal_to: 0.01, message: "流水金额大于0.01"
  validates_numericality_of :total, greater_than_or_equal_to: 0, message: "帐户总额必须大于等于0"

  scope :withdraw, -> {where(state: 1, transfer: 3).order(updated_at: :desc)}

  # default_scope { where(state: 1, transfer: 3, paid: false) }

  def show_hash
    {
      id: id,
      time: created_at.to_i,
      transfer: TRANSFER[transfer],
      amount: amount,
      info: extra_info 
    }
  end

  def extra_info
    case transfer
    when 2
      "来自订单 #{strategy_result.try(:order).try(:serial_number)}"
    when 3
      [account_bank, account_number].join(' ')
    else
      ''
    end
  end
#introducer_rebate_amount


  # 支付/充值
  def generate_pay(remote_ip="127.0.0.1")
    charge = self.pingpp_charge(payment_options(remote_ip))
    charge
  end

  # 提现
  def generate_withdraw
    transfer = self.pingpp_transfer(withdraw_options)
    transfer
  end

  def p_hash
    {
      order_no: "wallet#{id}",
      channel:  trade_type,
      amount:   amount * 100,
      currency: "cny",
      
    }
  end

  def payment_options(remote_ip="127.0.0.1")
    p_hash.merge(
      subject:   '支付/充值',
      body:      "充值： #{amount}",
      client_ip: remote_ip,
      extra:    extra_hash
    )
  end

  def extra_hash
    case trade_type
    when 'wx_pub'
      {open_id: user.open_id}
    when 'alipay_pc_direct'
      {success_url: "https://www.salesgj.com/#/app/pay?current=2"}
    end
  end

  def withdraw_options
    p_hash.merge(
      type:        "b2c",
      recipient:   user.mobile,
      description: "提现",
      extra:  _extra_hash   
    )
  end

  def _extra_hash
    {
      recipient_name: user.name
    }
  end

end

app/controllers/admin/wallet_logs_controller.rb
module Admin
  class WalletLogsController < Admin::ApplicationController
    before_filter :get_wlog, only: [:confirm_pay]
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = WalletLog.withdraw.order(updated_at: :desc).page(params[:page]).per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   WalletLog.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information

    def confirm_pay
        redirect_to(admin_wallet_logs_path, notice: '此单已确认付过款') if @wlog.try(:paid)
      if @wlog.update_attributes(paid: true)
        redirect_to admin_wallet_logs_path, notice: '已确认付款'
      else
        redirect_to admin_wallet_logs_path, notice: '操作失败请重新操作'
      end
    end

    private

    def get_wlog
      @wlog = WalletLog.find_by_id(params[:id])
    end
  end
end

app/views/admin/wallet_logs/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params.merge(
          collection_presenter.order_params_for(attr_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>

            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:confirm_pay, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <%= render_field attribute %>
          </td>
        <% end %>

        <% if resource.paid %>
          <td class="text-color-gray">已提现成功</td>
        <% else %>
          <td><%= link_to('确认支付', confirm_pay_admin_wallet_log_path(resource), method: :put, class: "text-color-red") %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/wallet_logs/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  提现列表
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <%= render(
    "search",
    search_term: search_term,
    resource_name: display_resource_name(page.resource_name)
  ) %>

</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources %>
</section>